### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [jamlol/f1-3-c2p1-colmar-academy#6]
### Criteria 1: HTML Structure  
* _Score Level:_ 4
* _Comment(s):_ HTML follows the flow of the page
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 4
* _Comment(s):_ Desktop and mobile layout matches the spec
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 4
* _Comment(s):_ Media quieries kick in at appropraite breakpoints
 
### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 4
* _Comment(s):_ CSS transitions were used, and consideration was made regarding typography along with the color palette.
 
### Overall Score: 16/16

Congrats on finishing your Capstone project! Overall you did an excellent job implementing all the required features of the spec sheet from the responsive layout to making use of CSS transitions. Apart from this, all your code was organized and readable, which was a consequence of making use of comments throughout your project code base.

To expand on your project consider researching the use of [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) and then analyze how you might make use of them. They are a great tool that allows you to increase the maintainability of your CSS file and it's readability.

**Comment by jamlol** [comment]
Thank you Jim!
